# Generated by Django 4.1.2 on 2022-10-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entregable2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='nacimiento',
        ),
    ]
